### ISSUE TITLE
how to use on nightly?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaTesting/TestEnv.jl#37]
I find currently because this package only registered on versions before 1.8, if a package CI uses this package on nightly then it would fail, any idea about setting up this?

**Comment by oxinabox** [comment]
We have a branch with julia 1.8 support
`] add TestEnv#release-1.8`

>  if a package CI uses this package on nightly 

It is weird for a package to depend on this in CI.
I am interested to hear the use-case

**Comment by Roger-luo** [comment]
My use case is that I have a few example projects need to run their own test while some of the dependencies are `dev`'ed, you can find the setup here https://github.com/comonicon/Comonicon.jl

there are two example projects `FakePkg` and `Hello` in `example` directory and they need to be run with `Comonicon` `dev`ed, and the test of `Comonicon` as well as its `lib/ComoniconTestUtils` needs to be run in an environment that both of the package is dev'ed
so I find `TestEnv` is quite convenient to create a shared environment for this.

**Comment by oxinabox** [comment]
should be resolved by new structure where we no longer block releases waiting for julia releases
