### ISSUE TITLE
release-1.10 branch?

### ISSUE THREAD

**Issue by timholy** [JuliaTesting/TestEnv.jl#52]
I'd submit a PR, except I don't think one can specify a non-existent branch as a merge target. Locally I was able to just split off `release-1.8` (which is more updated than `release-1.9`) and make `Project.toml` tweaks; so far, things seem to work, but I haven't given it a lot of testing.

One should ensure that all the flags that will soon affect precompilation get passed when precompilation occurs in the test environment. See https://github.com/JuliaLang/julia/pull/47184#issuecomment-1352768374.

**Comment by oxinabox** [comment]
good catch re-`release-1.9` being out of date. Fixing that now
and I will push a `release-1.10` presently
