### ISSUE TITLE
Is TestEnv.jl designed to be used with Test as extra in Project.toml or Test as deps in test/Project.toml?

### ISSUE THREAD

**Issue by martinmestre** [JuliaTesting/TestEnv.jl#88]
Thanks!
Besides I would like to know how to add an extra dependency in Project.toml apart from 
`> Pkg.add("Test", target=:extras)`
but using
`] add Test ...`

**Comment by oxinabox** [comment]
TestEnv.jl can't help you there.
The enviroment we create for testing is temporary.
Any changes made to it are lost.

It works with both Test/extras and test/Project.toml.
But it doesn't support making persistent changes to that enviroment.
Only using it.

I recommend asking on https://discourse.julialang.org/
how to do this.
I don't really know, myself I just edit Project.toml manually.
